package model.gui;

import model.classesExtras.EnumArquivoTxt;
import model.controle.EditoraControle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.classes.Editora;

/**
 * @author GUSTAVO
 *
 * @author JHONATHAN
 *
 * @author MIGUEL
 */
public class TelaDaEditora extends javax.swing.JFrame {

    EditoraControle controleEditora = null;
    Editora editoraAntiga = null;
    Editora editoraAtual = null;
    TelaLivro telaLivroExecutada = null;

    // lISTA DE COLABORADORES ATUALIZADA NA MEMORIA
    ArrayList<Editora> listaEditoras = new ArrayList<Editora>();

    /**
     * Creates new form TelaDaEditora
     */
    public TelaDaEditora() {
        initComponents();
        try {

            controleEditora = new EditoraControle(EnumArquivoTxt.EDITORA.getNomeDoArquivo());
            editoraAntiga = new Editora();
            editoraAtual = new Editora();

            // Atualiza a lista de colaborades com o contedo do arquivo
            listaEditoras = controleEditora.recuperar();

            //imprime a lista de colaboradores na grid
            imprimirDadosnaGrid(listaEditoras);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        this.setLocationRelativeTo(null);
    }

    private void limparTela() {

        String t = "";
        jTextFieldNome.setText(t);

    }

    private void imprimirDadosnaGrid(ArrayList<Editora> lista) {
        DefaultTableModel model = (DefaultTableModel) jTableDadosEditora.getModel();
        model.setNumRows(0);

        for (int pos = 0; pos < lista.size(); pos++) {

            String[] linha = new String[2];
            Editora aux = lista.get(pos);

            linha[0] = "" + aux.getId();
            linha[1] = aux.getNome().toUpperCase();

            model.addRow(linha);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIncluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonAlterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDadosEditora = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar/Pesquisar Editora");
        setMinimumSize(new java.awt.Dimension(1077, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonIncluir.setText("INCLUIR");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, 90, 50));

        jLabel2.setText("Incluir Editora");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 40));

        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 90, 50));

        jTableDadosEditora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableDadosEditora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ));
        jTableDadosEditora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDadosEditoraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableDadosEditora);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 584, 480));

        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 640, 90, 50));

        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, 90, 50));

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 480, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/imagem/magnifying-glass.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, 50));

        jLabel3.setText("Pesquisar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 30));

        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 480, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel17.setText("_ _ _ _ _ _ _ ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 70, 30));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel6.setText("F A T E S G ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, 20));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel18.setText("B i b l i o ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 100, 40));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("_ _ _ _ _ _ _ _ _ ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 90, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel7.setText("P r o j e t o");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 20));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText(" t e c h");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/imagem/blur corte tela principal.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed

        try {

            editoraAtual.setNome(jTextFieldNome.getText());

            controleEditora.incluir(editoraAtual);

            limparTela();

            imprimirDadosnaGrid(controleEditora.recuperar());

            listaEditoras = controleEditora.recuperar();

            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }

    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed

        try {

            editoraAtual.setId(editoraAntiga.getId());

            editoraAtual.setNome(jTextFieldNome.getText());

            controleEditora.alterarEditora(editoraAntiga, editoraAtual);

            imprimirDadosnaGrid(controleEditora.recuperar());

            limparTela();

            JOptionPane.showMessageDialog(rootPane, "Alteração Realizada com sucesso");

            listaEditoras = controleEditora.recuperar();

        } catch (Exception erro) {
            JOptionPane.showConfirmDialog(rootPane, erro);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    public void preencherFormulario() {

        String posicaoId = jTableDadosEditora.getValueAt(jTableDadosEditora.getSelectedRow(), 0).toString().toUpperCase();
        String posicaoNome = jTableDadosEditora.getValueAt(jTableDadosEditora.getSelectedRow(), 1).toString().toUpperCase();

        jTextFieldNome.setText(posicaoNome);

        editoraAntiga.setId(Integer.parseInt(posicaoId));
        editoraAntiga.setNome(posicaoNome);

    }


    private void jTableDadosEditoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDadosEditoraMouseClicked

        try {

            preencherFormulario();

        } catch (Exception erro) {
            JOptionPane.showConfirmDialog(rootPane, erro);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTableDadosEditoraMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        try {

            if (jTextFieldNome.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Selecione um nome para excluir !", "ERRO", JOptionPane.ERROR_MESSAGE);
            } else {

                controleEditora.excluir(editoraAntiga.getId());

                imprimirDadosnaGrid(controleEditora.recuperar());

                limparTela();

                JOptionPane.showMessageDialog(rootPane, "Exclusão Realizada com sucesso");

                listaEditoras = controleEditora.recuperar();

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed

       telaLivroExecutada.AtualizaComboEditora();
        telaLivroExecutada.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed

        try {

            String textoDigitado = jTextFieldPesquisar.getText().toLowerCase(); // texto digitado na jtextfield em minuscula

            ArrayList<Editora> resultadoPesquisa = new ArrayList<>(); //lista vazia com o resultado da pesquisa

            for (Editora editora : listaEditoras) {//colaboradores == lista recuperada do arquivo

                if ((editora.getNome().toLowerCase().trim().contains(textoDigitado)) //varre o nome

                        || (("" + editora.getId()).toLowerCase().trim().contains(textoDigitado))) { // varre o id

                    resultadoPesquisa.add(editora); // INCLUI O RESULTADO ENCONTRADO NA LISTA
                }
            }
            imprimirDadosnaGrid(resultadoPesquisa);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed
    public void manterTelaLivroAntiga(TelaLivro telalivro){
        telaLivroExecutada = telalivro;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDaEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDaEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDaEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDaEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDaEditora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDadosEditora;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
