/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.gui;

import model.classes.Area;
import model.controle.AreaControle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.classesExtras.EnumArquivoTxt;
import model.classesExtras.EnumCDD;

/**
 * @author GUSTAVO
 *
 * @author JHONATHAN
 *
 * @author MIGUEL
 */
public class TelaAreaDoLivro extends javax.swing.JFrame {

    AreaControle controleArea = null;
    Area areaAntiga = null;
    Area areaAtual = null;
    TelaLivro TelaLivroExecutada = null;

    // lISTA DE COLABORADORES ATUALIZADA NA MEMORIA
    ArrayList<Area> listaDeArea = new ArrayList<Area>();

    /**
     * Creates new form TelaAreaDoLivro
     */
    public TelaAreaDoLivro() {
        initComponents();
        try {

            controleArea = new AreaControle(EnumArquivoTxt.AREADOLIVRO.getNomeDoArquivo());
            areaAntiga = new Area();
            areaAtual = new Area();

            // Atualiza a lista de colaborades com o contedo do arquivo
            listaDeArea = controleArea.recuperar();
            //imprime a lista de colaboradores na grid
            imprimirDadosnaGrid(listaDeArea);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        this.setLocationRelativeTo(null);

    }

    public void preencherFormulario() {

        String posicaoId = jTableDadosAreaDoLivro.getValueAt(jTableDadosAreaDoLivro.getSelectedRow(), 0).toString().toUpperCase();
        String posicaoNome = jTableDadosAreaDoLivro.getValueAt(jTableDadosAreaDoLivro.getSelectedRow(), 1).toString().toUpperCase();
        String posicaoCdd = jTableDadosAreaDoLivro.getValueAt(jTableDadosAreaDoLivro.getSelectedRow(), 2).toString().toUpperCase();

        jComboBoxCdd.setSelectedItem(posicaoCdd);
        areaAntiga.setId(Integer.parseInt(posicaoId));
        areaAntiga.setNomeArea(posicaoNome);

    }

    private void imprimirDadosnaGrid(ArrayList<Area> lista) {
        DefaultTableModel model = (DefaultTableModel) jTableDadosAreaDoLivro.getModel();
        model.setNumRows(0);

        for (int pos = 0; pos < lista.size(); pos++) {

            String[] linha = new String[3];
            Area aux = lista.get(pos);

            linha[0] = "" + aux.getId();
            linha[1] = aux.getNomeArea().toUpperCase();
            linha[2] = "" + aux.getCdd().getTipo();

            model.addRow(linha);

        }
    }

    private void limparTela() {

        String t = "";
        jComboBoxCdd.setSelectedItem(t);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDadosAreaDoLivro = new javax.swing.JTable();
        jButtonIncluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxCdd = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar/Pesquisar Área Jurídica do Livro");
        setMaximumSize(new java.awt.Dimension(1077, 720));
        setMinimumSize(new java.awt.Dimension(1077, 720));
        setPreferredSize(new java.awt.Dimension(1077, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Incluir Área  ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, 40));

        jTableDadosAreaDoLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ÁREA", "CÓDIGO CDD"
            }
        ));
        jTableDadosAreaDoLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDadosAreaDoLivroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDadosAreaDoLivro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 569, 480));

        jButtonIncluir.setText("INCLUIR");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 90, 50));

        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 640, 90, 50));

        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, 90, 50));

        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, 90, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/imagem/magnifying-glass.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 30, 50));

        jLabel4.setText("Pesquisar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 70, 30));

        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 470, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel17.setText("_ _ _ _ _ _ _ ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 70, 30));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel6.setText("F A T E S G ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, 20));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel18.setText("B i b l i o ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 100, 40));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("_ _ _ _ _ _ _ _ _ ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 90, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel7.setText("P r o j e t o");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 20));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText(" t e c h");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, 20));

        jComboBoxCdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DIREITO", "DIREITO_PUBLICO", "DIREITO_INTERNACIONALPÚBLICO", "DIREITO_PENAL_INTERNACIONAL", "DIREITO_CONSTITUCIONAL", "DIREITOS_FUNDAMENTAIS", "DIREITO_ELEITORAL", "DIREITO_ADMINISTRATIVO", "DIREITO_AMBIENTAL", "DIREITO_ECONÔMICO", "DIREITO_FINANCEIRO", "DIREITO_TRIBUTÁRIO", "DIREITO_PROCESSUAL", "DIREITO_PROCESSUAL_PENAL", "DIREITO_PROCESSUAL_CIVIL", "DIREITO_PENAL", "DIREITO_PENITENCIÁRIO_DIREITO_DE_EXECUÇÕES_PENAIS", "DIREITO_PREVIDENCIÁRIO_SEGURIDADE_SOCIAL", "DIREITO_MILITAR", "DIREITO_PENAL_MILITAR", "DIREITO_AÉREO_CÓDIGO_DO_AR", "DIREITO_AÉREO_MILITAR", "DIREITO_APLICADO_À_TELECOMUNICAÇÃO", "DIREITO_ESPACIAL", "DIREITO_PRIVADO", "DIREITO_CIVIL", "DIREITO_DAS_COISAS_DIREITOS_REAIS_COISAS_E_BENS", "DIREITO_DE_FAMÍLIA", "DIREITO_DAS_SUCESSÕES", "DIREITO_DO_MENOR", "DIREITO_COMERCIAL", "DIREITO_BANCÁRIO", "DIREITOS_INTELECTUAIS_PROPRIEDADE_INDUSTRIAL", "DIREITO_AUTORAL_DIREITO_ARTÍSTICO_E_LITERÁRIO", "DIREITO_MARÍTIMO", "DIREITO_AERONÁUTICO", "DIREITO_INTERNACIONAL_PRIVADO", "DIREITO_DO_CONSUMIDOR", "DIREITO_DO_TRABALHO", "DIREITO_PROCESSUAL_DO_TRABALHO" }));
        jComboBoxCdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCddActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 470, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/imagem/blur corte tela principal.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed

        try {

            areaAtual.setId(areaAntiga.getId());
            areaAtual.setNomeArea(jComboBoxCdd.getSelectedItem().toString());
            areaAtual.setCdd(EnumCDD.valueOf(jComboBoxCdd.getSelectedItem().toString()));

            controleArea.incluir(areaAtual);

            imprimirDadosnaGrid(controleArea.recuperar());

            listaDeArea = controleArea.recuperar();

            limparTela();
             
            JOptionPane.showMessageDialog(rootPane, "Cadastro realizado com sucesso!");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed

        try {

            areaAtual.setId(areaAntiga.getId());
            areaAtual.setNomeArea(jComboBoxCdd.getSelectedItem().toString());
            areaAtual.setCdd(EnumCDD.valueOf(jComboBoxCdd.getSelectedItem().toString()));

            controleArea.alterarArea(areaAntiga, areaAtual);

            imprimirDadosnaGrid(controleArea.recuperar());

            limparTela();

            JOptionPane.showMessageDialog(null, "Alteração Realizada com sucesso");

            listaDeArea = controleArea.recuperar();

        } catch (Exception erro) {
            JOptionPane.showConfirmDialog(null, erro);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTableDadosAreaDoLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDadosAreaDoLivroMouseClicked

        try {

            preencherFormulario();

        } catch (Exception erro) {
            JOptionPane.showConfirmDialog(null, erro);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTableDadosAreaDoLivroMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        try {

            controleArea.excluir(areaAntiga.getId());

            imprimirDadosnaGrid(controleArea.recuperar());

            limparTela();

            JOptionPane.showMessageDialog(rootPane, "Exclusão Realizada com sucesso");

            listaDeArea = controleArea.recuperar();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaLivroExecutada.AtualizaComboArea(); 
        TelaLivroExecutada.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed

        try {

            String textoDigitado = jTextFieldPesquisar.getText().toLowerCase(); // texto digitado na jtextfield em minuscula

            ArrayList<Area> resultadoPesquisa = new ArrayList<>(); //lista vazia com o resultado da pesquisa
            //colaboradores == lista recuperada do arquivo
            for (Area areaDolivro : listaDeArea) {

                if ((("" + areaDolivro.getId()).toLowerCase().trim().contains(textoDigitado))
                        || (("" + areaDolivro.getCdd().getTipo()).toLowerCase().trim().contains(textoDigitado))
                        || (("" + areaDolivro.getCdd()).toLowerCase().trim().contains(textoDigitado))) {

                    resultadoPesquisa.add(areaDolivro); // INCLUI O RESULTADO ENCONTRADO NA LISTA
                }
            }
            imprimirDadosnaGrid(resultadoPesquisa);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed

    private void jComboBoxCddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCddActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCddActionPerformed

     public void manterTelaLivroAntiga(TelaLivro telalivro){
       TelaLivroExecutada = telalivro;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAreaDoLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAreaDoLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAreaDoLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAreaDoLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAreaDoLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxCdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDadosAreaDoLivro;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
