/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.gui;

import model.classesExtras.EnumArquivoTxt;
import model.classesExtras.TipoDeStatus;
import model.controle.EmprestimoControle;
import model.controle.ExemplarControle;
import model.controle.LivroControle;
import model.controle.ColaboradorControle;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import model.classes.Emprestimo;
import model.classes.Exemplar;
import model.classes.Livro;
import model.classes.Colaborador;

/**
 * @author GUSTAVO
 *
 * @author JHONATHAN
 *
 * @author MIGUEL
 */
public class TelaEmprestimo extends javax.swing.JFrame {
    
    TelaMulta enviadados;

    ExemplarControle controleExemplar = null;
    EmprestimoControle controleEmprestimo = null;
    LivroControle controleLivro = null;
    ColaboradorControle controleColaborador = null;
    Emprestimo EmprestimoAntigo = null;
    Emprestimo EmprestimoAtual = null;
    Exemplar ExemplarAntigo = null;
    Exemplar ExemplarAtual = null;

    //Lista de emprestimos atualizada na memoria
    ArrayList<Emprestimo> listaEmprestimos = new ArrayList<Emprestimo>();

    /**
     * Creates new form TelaEmprestimo
     */
    public TelaEmprestimo() {
        initComponents();
        try {
            controleLivro = new LivroControle(EnumArquivoTxt.LIVRO.getNomeDoArquivo());
            controleExemplar = new ExemplarControle(EnumArquivoTxt.EXEMPLAR.getNomeDoArquivo());
            controleEmprestimo = new EmprestimoControle(EnumArquivoTxt.EMPRESTIMO.getNomeDoArquivo());
            controleColaborador = new ColaboradorControle(EnumArquivoTxt.COLABORADOR.getNomeDoArquivo());
            EmprestimoAntigo = new Emprestimo();
            EmprestimoAtual = new Emprestimo();
            formatarCampoParaDataEmprestimo();

            formatarCampoParaDataQueDevolveu();
            jFormattedTextField_DiaQueDevolveu.setEnabled(false);

            jButton_OKdevolucao.setEnabled(false);
            jButton_CancelarDevolucao.setEnabled(false);
            jFormattedTextField_DT_EMPRESTIMO.setEnabled(false);
            jTextField_DataDeveraDevolver.setEnabled(false);
            jTextFieldMulta.setEnabled(false);
             jButton_Cupom.setEnabled(false);

            jTextFieldMulta.setText("R$ 2,00 ao dia");

            ArrayList<Livro> listaLivro = controleLivro.recuperar();
            for (Livro livro : listaLivro) {
                jComboBoxlivro.addItem(livro.getTitulo().toUpperCase());
            }

            ArrayList<Colaborador> listaNovoColaborador = controleColaborador.recuperar();
            for (Colaborador colaborador : listaNovoColaborador) {
                jComboBox_NomeColaborador.addItem(colaborador.getNome().toUpperCase());
            }

            //Imprime a lista de emprestimos na grid ao iniciar o programa
            listaEmprestimos = controleEmprestimo.recuperar();
            imprimirDadosNaGrid(listaEmprestimos);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonIncluir = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonVolatr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMulta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxlivro = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldQuantidadeDisponivel = new javax.swing.JTextField();
        jFormattedTextField_DT_EMPRESTIMO = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox_NomeColaborador = new javax.swing.JComboBox();
        jButton_Devolucao = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextField_DiaQueDevolveu = new javax.swing.JFormattedTextField();
        jButton_OKdevolucao = new javax.swing.JButton();
        jButton_CancelarDevolucao = new javax.swing.JButton();
        jTextField_DataDeveraDevolver = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmprestimo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton_Cupom = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emprestar/Pesquisar/Devolver/Cupom  Empréstimo do Livro");
        setMinimumSize(new java.awt.Dimension(1077, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 820, -1));

        jLabel6.setText("Pesquisar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 40));

        jButtonIncluir.setText("EMPRESTAR");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 110, 50));

        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, 110, 50));

        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 110, 50));

        jButtonVolatr.setText("VOLTAR");
        jButtonVolatr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolatrActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolatr, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 110, 50));

        jLabel2.setText("Multa Por Atraso");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, -1, 50));

        jLabel3.setText("Data Emprestimo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, -1, 30));
        getContentPane().add(jTextFieldMulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 120, 30));

        jLabel4.setText("Data da Devolução");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/imagem/magnifying-glass.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, 60));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel17.setText("_ _ _ _ _ _ _ ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 70, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel7.setText("F A T E S G ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, 20));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel18.setText("B i b l i o ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 100, 40));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("_ _ _ _ _ _ _ _ _ ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 90, 30));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel8.setText("P r o j e t o");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 20));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText(" t e c h");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, 20));

        jLabel11.setText("Livro");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 50));

        jComboBoxlivro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Livro" }));
        jComboBoxlivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxlivroActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxlivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 300, -1));

        jLabel12.setText("Unidade(s) Disponíveis");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, 30));

        jTextFieldQuantidadeDisponivel.setEnabled(false);
        getContentPane().add(jTextFieldQuantidadeDisponivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 70, -1));
        getContentPane().add(jFormattedTextField_DT_EMPRESTIMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 120, 30));

        jLabel13.setText("Colaborador");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        jComboBox_NomeColaborador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o nome do Colaborador " }));
        getContentPane().add(jComboBox_NomeColaborador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 520, 30));

        jButton_Devolucao.setText("DEVOLVER");
        jButton_Devolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DevolucaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Devolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 110, 50));

        jLabel10.setText("Data da Devolução");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));
        getContentPane().add(jFormattedTextField_DiaQueDevolveu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 130, 30));

        jButton_OKdevolucao.setText("OK");
        jButton_OKdevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKdevolucaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_OKdevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 50, 30));

        jButton_CancelarDevolucao.setText("CANCELAR");
        jButton_CancelarDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarDevolucaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CancelarDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, 30));
        getContentPane().add(jTextField_DataDeveraDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 120, 30));

        jTableEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME DO COLABORADOR", "TÍTULO DO LIVRO", "DATA DE EMPRESTIMO", "STATUS DO EMPRESTIMO"
            }
        ));
        jTableEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmprestimoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmprestimo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 950, 320));

        jLabel1.setText(" Informações do Emprestimo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, 20));

        jButton_Cupom.setText("CUPOM");
        jButton_Cupom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CupomActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Cupom, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 620, 110, 50));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 20, 140));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/imagem/blur corte tela principal.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //METODOS  
    private void limparTela() {

        String t = "";
        jTextField_DataDeveraDevolver.setText(t);
        jFormattedTextField_DT_EMPRESTIMO.setText(t);
        jFormattedTextField_DiaQueDevolveu.setText(t);
        jTextFieldPesquisar.setText(t);
        jComboBoxlivro.setSelectedIndex(0);
        jComboBox_NomeColaborador.setSelectedIndex(0);

    }

    private String getDateTime() {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        return dateFormat.format(date);
    }

    private void formatarCampoParaDataEmprestimo() {
        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            mascara.install(jFormattedTextField_DT_EMPRESTIMO);

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir data", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void formatarCampoParaDataQueDevolveu() {
        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            mascara.install(jFormattedTextField_DiaQueDevolveu);

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir data", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void imprimirDadosNaGrid(ArrayList<Emprestimo> lista) {

        DefaultTableModel model = (DefaultTableModel) jTableEmprestimo.getModel();
        model.setNumRows(0);

        String[] linha = new String[5];
        for (int pos = 0; pos < lista.size(); pos++) {

            Emprestimo aux = lista.get(pos);

            linha[0] = "" + aux.getId();
            linha[1] = "" + aux.getNomeColaborador().getNome().toUpperCase();
            linha[2] = "" + aux.getLivro().getTitulo().toUpperCase();
            linha[3] = "" + new SimpleDateFormat("dd/MM/yyyy").format(aux.getDataEmprestimo());
            linha[4] = "" + aux.getStatus();

            model.addRow(linha);

        }
    }

    public void preencherFormulario() throws Exception {

        String posicaoId = jTableEmprestimo.getValueAt(jTableEmprestimo.getSelectedRow(), 0).toString().toUpperCase();
        String posicaoNomeColaborador = jTableEmprestimo.getValueAt(jTableEmprestimo.getSelectedRow(), 1).toString().toUpperCase();
        String posicaoDoLivro = jTableEmprestimo.getValueAt(jTableEmprestimo.getSelectedRow(), 2).toString().toUpperCase();
        String posicaoDataEmprestimo = jTableEmprestimo.getValueAt(jTableEmprestimo.getSelectedRow(), 3).toString().toUpperCase();

        EmprestimoAntigo.setId(Integer.parseInt(posicaoId));
        jComboBoxlivro.setSelectedItem(posicaoDoLivro);
        jComboBox_NomeColaborador.setSelectedItem(posicaoNomeColaborador);
        jFormattedTextField_DT_EMPRESTIMO.setText(posicaoDataEmprestimo);

        String aux = posicaoDataEmprestimo;

        DateTimeFormatter parser = DateTimeFormatter.ofPattern("dd/MM/uuuu");
        LocalDate data = LocalDate.parse(aux, parser);    //Converte Dete pra LocalDate para acrecentar diaas
        LocalDate diaSeguinte = data.plusDays(7);
        jTextField_DataDeveraDevolver.setText("" + diaSeguinte.getDayOfMonth() + "/" + data.getMonthValue() + "/" + data.getYear());

    }
    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        try {

            ArrayList<Exemplar> listaDosExemplares = controleExemplar.recuperar();
            ArrayList<Exemplar> exemplaresDISPONIVEIS = new ArrayList<>();
            int i = 0;
            for (Exemplar exemplar : listaDosExemplares) {
                if (exemplar.getLivro().getTitulo().equalsIgnoreCase(jComboBoxlivro.getSelectedItem().toString())) {
                    if (exemplar.getTipoDeStatus().equals(exemplar.getTipoDeStatus().DISPONIVEL)) {
                        i++;

                        exemplaresDISPONIVEIS.add(exemplar);

                    }

                }

            }

            EmprestimoAtual.setExemplar(exemplaresDISPONIVEIS.get(0));
            EmprestimoAtual.setDataEmprestimo(new SimpleDateFormat("dd/MM/yyyy").parse(getDateTime()));
            EmprestimoAtual.setLivro(controleLivro.recuperar(jComboBoxlivro.getSelectedItem().toString()));
            EmprestimoAtual.setNomeColaborador(controleColaborador.recuperar(jComboBox_NomeColaborador.getSelectedItem().toString()));
            EmprestimoAtual.setStatus(TipoDeStatus.ATIVO);

            ExemplarAntigo = EmprestimoAtual.getExemplar();
            ExemplarAtual = ExemplarAntigo;
            
            ExemplarAtual.setTipoDeStatus(TipoDeStatus.EMPRESTADO);   //ALTERA O STATUS DO EXEMPLAR AO DEVOLVELO PARA DISPONIVEL
            controleExemplar.alterar(ExemplarAntigo, ExemplarAtual);

            controleEmprestimo.incluir(EmprestimoAtual);

            imprimirDadosNaGrid(controleEmprestimo.recuperar());

            
            
//          
            limparTela();

            JOptionPane.showMessageDialog(rootPane, "Emprestimo Realizado com Sucesso!\n Cupom Enviado para o E-mail\n("+EmprestimoAtual.getNomeColaborador().getEmail()+")");

            listaEmprestimos = controleEmprestimo.recuperar();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        try {

            String posicaoId = jTableEmprestimo.getValueAt(jTableEmprestimo.getSelectedRow(), 0).toString().toUpperCase();  // PEGA O ID DO EMPRESTIMO AO SELECIONAR A LINHA
            Emprestimo objeto = controleEmprestimo.recuperar(Integer.parseInt(posicaoId));  //RECUPERA O OBJETO PELO ID CAPTURADO
            ExemplarAntigo = objeto.getExemplar();
            ExemplarAtual = ExemplarAntigo;
            ExemplarAtual.setTipoDeStatus(TipoDeStatus.DISPONIVEL);   //ALTERA O STATUS DO EXEMPLAR AO DEVOLVELO PARA DISPONIVEL
            controleExemplar.alterar(ExemplarAntigo, ExemplarAtual);
            controleEmprestimo.excluir(EmprestimoAntigo.getId());

            imprimirDadosNaGrid(controleEmprestimo.recuperar());

            limparTela();

            JOptionPane.showMessageDialog(rootPane, "Exclusão Realizada com sucesso!");

            listaEmprestimos = controleEmprestimo.recuperar();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        try {
            ArrayList<Exemplar> listaDosExemplares = controleExemplar.recuperar();
            ArrayList<Exemplar> exemplaresDISPONIVEIS = new ArrayList<>();
            int i = 0;
            for (Exemplar exemplar : listaDosExemplares) {
                if (exemplar.getLivro().getTitulo().equalsIgnoreCase(jComboBoxlivro.getSelectedItem().toString())) {
                    if (exemplar.getTipoDeStatus().equals(exemplar.getTipoDeStatus().DISPONIVEL)) {
                        i++;

                        exemplaresDISPONIVEIS.add(exemplar);

                    }

                }

            }

            EmprestimoAtual.setExemplar(exemplaresDISPONIVEIS.get(0));

            EmprestimoAtual.setId(EmprestimoAntigo.getId());
            EmprestimoAtual.setDataEmprestimo(new SimpleDateFormat("dd/MM/yyyy").parse(jFormattedTextField_DT_EMPRESTIMO.getText()));
            EmprestimoAtual.setLivro(controleLivro.recuperar(jComboBoxlivro.getSelectedItem().toString()));
            EmprestimoAtual.setNomeColaborador(controleColaborador.recuperar(jComboBox_NomeColaborador.getSelectedItem().toString()));

            ExemplarAntigo = EmprestimoAtual.getExemplar();
            ExemplarAtual = ExemplarAntigo;
            ExemplarAtual.setTipoDeStatus(TipoDeStatus.EMPRESTADO);   //ALTERA O STATUS DO EXEMPLAR AO DEVOLVELO PARA DISPONIVEL
            controleExemplar.alterar(ExemplarAntigo, ExemplarAtual);

            controleEmprestimo.alterar(EmprestimoAntigo, EmprestimoAtual);

            imprimirDadosNaGrid(controleEmprestimo.recuperar());

            limparTela();

            JOptionPane.showMessageDialog(rootPane, "Alteração Realizada com sucesso!");

            listaEmprestimos = controleEmprestimo.recuperar();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonVolatrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolatrActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonVolatrActionPerformed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed

        try {
            //Texto digitado na jtextfield em minuscula
            String textoDigitado = jTextFieldPesquisar.getText().toLowerCase();

            //Lista vazia com o resultado da pesquisa
            ArrayList<Emprestimo> resultadoPesquisa = new ArrayList<>();

            //Emprestimo == lista recuperada do arquivo
            for (Emprestimo emprestimo : listaEmprestimos) {

                if (emprestimo.getExemplar().getLivro().getTitulo().toLowerCase().trim().contains(textoDigitado)
                        || (("" + emprestimo.getDataEmprestimo()).toLowerCase().trim().contains(textoDigitado))
                        || (("" + emprestimo.getId()).toLowerCase().trim().contains(textoDigitado))) {

                    //Inclui o resultado encontrado na pesquisa    
                    resultadoPesquisa.add(emprestimo);
                }
            }
            imprimirDadosNaGrid(resultadoPesquisa);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed

    private void jButton_DevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DevolucaoActionPerformed

        jComboBoxlivro.setEnabled(false);

        jComboBox_NomeColaborador.setEnabled(false);
        jTextField_DataDeveraDevolver.setEnabled(false);
        jFormattedTextField_DT_EMPRESTIMO.setEnabled(false);
        jTextFieldMulta.setEnabled(false);

        jFormattedTextField_DiaQueDevolveu.setEnabled(true);
        jButton_OKdevolucao.setEnabled(true);
        jButton_CancelarDevolucao.setEnabled(true);


    }//GEN-LAST:event_jButton_DevolucaoActionPerformed

    private void jButton_OKdevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKdevolucaoActionPerformed
        try {
            
            
            String posicaoId = jTableEmprestimo.getValueAt(jTableEmprestimo.getSelectedRow(), 0).toString().toUpperCase();  // PEGA O ID DO EMPRESTIMO AO SELECIONAR A LINHA
            Emprestimo objetoEmprestimoAntigo = controleEmprestimo.recuperar(Integer.parseInt(posicaoId));  //RECUPERA O OBJETO PELO ID CAPTURADO
            
            String posicaoNomeColaborador = jTableEmprestimo.getValueAt(jTableEmprestimo.getSelectedRow(), 1).toString().toUpperCase();
            
            
            String DataEmprestimo = jTableEmprestimo.getValueAt(jTableEmprestimo.getSelectedRow(), 3).toString().toUpperCase();
            
            String DiaQueDevolveu = jFormattedTextField_DiaQueDevolveu.getText(); // pega os dados digitados da devolução e joga na String

            ExemplarAntigo = objetoEmprestimoAntigo.getExemplar();
            ExemplarAtual = ExemplarAntigo;
            ExemplarAtual.setTipoDeStatus(TipoDeStatus.DISPONIVEL);   //ALTERA O STATUS DO EXEMPLAR E DO EMPRESTIMO AO DEVOLVELO PARA DISPONIVEL
            controleExemplar.alterar(ExemplarAntigo, ExemplarAtual);
            Emprestimo ObjetoEmprestimoAtual = objetoEmprestimoAntigo;
            ObjetoEmprestimoAtual.setStatus(TipoDeStatus.FINALIZADO);
            controleEmprestimo.alterar(objetoEmprestimoAntigo,ObjetoEmprestimoAtual);
            
            

            imprimirDadosNaGrid(controleEmprestimo.recuperar());
            limparTela();
            listaEmprestimos = controleEmprestimo.recuperar();

            jComboBoxlivro.setEnabled(true);

            jComboBox_NomeColaborador.setEnabled(true);
            

            jFormattedTextField_DiaQueDevolveu.setEnabled(false);
            jButton_OKdevolucao.setEnabled(false);
            jButton_CancelarDevolucao.setEnabled(false);
            
             Date dataFormatada = new SimpleDateFormat("dd/MM/yyyy").parse(DiaQueDevolveu);  // Converte as Strings em Date
             Date dataFormatada2 = new SimpleDateFormat("dd/MM/yyyy").parse(DataEmprestimo);
             
             DateTimeFormatter parser = DateTimeFormatter.ofPattern("dd/MM/uuuu");
             LocalDate data = LocalDate.parse(DataEmprestimo, parser);    //Converte Dete pra LocalDate para acrecentar diaas
             LocalDate diaSeguinte = data.plusDays(7);
             
             Date dataQueDeveDevolver = Date.from(diaSeguinte.atStartOfDay(ZoneId.systemDefault()).toInstant());// converte de LocalDatePara Datepara comparar
             
             long diferencaMS = dataFormatada.getTime() - dataQueDeveDevolver.getTime();  // PARA COMPARAR QUANTOS DIAS DE ATRAAZO TEVE
             long diferencaSegundos = diferencaMS / 1000;
             long diferencaMinutos = diferencaSegundos / 60;
             long diferencaHoras = diferencaMinutos / 60;
             long diferencaDias = diferencaHoras / 24;
             
             
             
             if (dataFormatada.compareTo(dataQueDeveDevolver) <= 0) { // Comprara a data que deveria devolver com a digitaada
                 
                 JOptionPane.showMessageDialog(null,"Devolvido no prazo correto");
                 
             } else {
                   TelaEmprestimo telaEmprestimo = this;
                 
                 TelaMulta chamaTela = new TelaMulta();
                 chamaTela.recebendo(posicaoNomeColaborador, DataEmprestimo, DiaQueDevolveu, telaEmprestimo);
                 chamaTela.setVisible(true);
               
             }
        } catch (ParseException ex) {
            Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_OKdevolucaoActionPerformed

    private void jButton_CancelarDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarDevolucaoActionPerformed
        jComboBoxlivro.setEnabled(true);

        jComboBox_NomeColaborador.setEnabled(true);
        jTextField_DataDeveraDevolver.setEnabled(true);
        jFormattedTextField_DT_EMPRESTIMO.setEnabled(true);
        jTextFieldMulta.setEnabled(true);

        jFormattedTextField_DiaQueDevolveu.setEnabled(false);
        jButton_OKdevolucao.setEnabled(false);
        jButton_CancelarDevolucao.setEnabled(false);

        limparTela();
    }//GEN-LAST:event_jButton_CancelarDevolucaoActionPerformed

    private void jComboBoxlivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxlivroActionPerformed
        try {
            ArrayList<Exemplar> listaDosExemplares = controleExemplar.recuperar();
            int i = 0;
            for (Exemplar exemplar : listaDosExemplares) {
                if (exemplar.getLivro().getTitulo().equalsIgnoreCase(jComboBoxlivro.getSelectedItem().toString())) {
                    if (exemplar.getTipoDeStatus().equals(exemplar.getTipoDeStatus().DISPONIVEL)) {
                        i++;
                    }

                }

            }
            jTextFieldQuantidadeDisponivel.setText("" + i);

        } catch (Exception ex) {
            Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxlivroActionPerformed

    private void jTableEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmprestimoMouseClicked
        try {
            
            jButton_Cupom.setEnabled(true);

            preencherFormulario();

        } catch (Exception ex) {
            Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableEmprestimoMouseClicked

    private void jButton_CupomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CupomActionPerformed
        try {
            String posicaoId = jTableEmprestimo.getValueAt(jTableEmprestimo.getSelectedRow(), 0).toString().toUpperCase();
            Emprestimo ObjetoEmpreestimo =  controleEmprestimo.recuperar(Integer.parseInt(posicaoId));
             
            SimpleDateFormat dataformatada = new SimpleDateFormat("dd/MM/yyyy");
            String DataEmprestimo = dataformatada.format(ObjetoEmpreestimo.getDataEmprestimo());
            
            DateTimeFormatter parser = DateTimeFormatter.ofPattern("dd/MM/uuuu");
            LocalDate data = LocalDate.parse(DataEmprestimo, parser);    //Converte Dete pra LocalDate para acrecentar diaas
            LocalDate diaSeguinte = data.plusDays(7);
            

            String dataDevolucao = ("" + diaSeguinte.getDayOfMonth() + "/" + data.getMonthValue() + "/" + data.getYear());
            String dataParaCupom =  ("" + data.getDayOfMonth() + "/" + data.getMonthValue() + "/" + data.getYear());
            
          String saida ="-----------------CUPOM EMPRESTIMO-----------------\n";
          saida+="NOME: "+ObjetoEmpreestimo.getNomeColaborador().getNome()+"\n";
          saida+= "LIVRO: "+ObjetoEmpreestimo.getLivro().getTitulo()+"\n";
          saida+= "EXEMPLAR: "+ObjetoEmpreestimo.getExemplar().getId()+"\n";
          saida+= "DATA EMPRESTIMO: "+dataParaCupom+"\n";
          saida+= "DATA DEVOLUÇÃO: "+dataDevolucao+"\n";
          saida+= "---------------------------------------------------------\n\n";
          
          
          JOptionPane.showMessageDialog(null, saida);
            
        } catch (Exception ex) {
            Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_CupomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonVolatr;
    private javax.swing.JButton jButton_CancelarDevolucao;
    private javax.swing.JButton jButton_Cupom;
    private javax.swing.JButton jButton_Devolucao;
    private javax.swing.JButton jButton_OKdevolucao;
    private javax.swing.JComboBox jComboBox_NomeColaborador;
    private javax.swing.JComboBox<String> jComboBoxlivro;
    private javax.swing.JFormattedTextField jFormattedTextField_DT_EMPRESTIMO;
    private javax.swing.JFormattedTextField jFormattedTextField_DiaQueDevolveu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableEmprestimo;
    private javax.swing.JTextField jTextFieldMulta;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldQuantidadeDisponivel;
    private javax.swing.JTextField jTextField_DataDeveraDevolver;
    // End of variables declaration//GEN-END:variables
}
