/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.gui;

import model.classesExtras.EnumArquivoTxt;
import model.controle.AutorControle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.classes.Autor;

/**
 * @author GUSTAVO
 *
 * @author JHONATHAN
 *
 * @author MIGUEL
 */
public class TelaDoAutor extends javax.swing.JFrame {

    AutorControle controleAutor = null;
    Autor autorAntiga = null;
    Autor autorAtual = null;
    TelaLivro TelaLivroExecutada = null;

    // lISTA DE COLABORADORES ATUALIZADA NA MEMORIA
    ArrayList<Autor> listaAutores = new ArrayList<Autor>();

    /**
     * Creates new form TelaDoAutor
     */
    public TelaDoAutor() {
        initComponents();

        try {

            controleAutor = new AutorControle(EnumArquivoTxt.AUTOR.getNomeDoArquivo());
            autorAntiga = new Autor();
            autorAtual = new Autor();

            // Atualiza a lista de colaborades com o contedo do arquivo
          listaAutores = controleAutor.recuperar();

            //imprime a lista de colaboradores na grid
            imprimirDadosnaGrid(listaAutores);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        this.setLocationRelativeTo(null);
    }

    private void limparTela() {

        String t = "";
        jTextFieldNome.setText(t);

    }

    private void imprimirDadosnaGrid(ArrayList<Autor> lista) {
        DefaultTableModel model = (DefaultTableModel) jTableDadosAutor.getModel();
        model.setNumRows(0);

        for (int pos = 0; pos < lista.size(); pos++) {

            String[] linha = new String[2];
            Autor aux = lista.get(pos);

            linha[0] = "" + aux.getId();
            linha[1] = aux.getNomeAutor().toUpperCase();

            model.addRow(linha);

        }
    }

    public void preencherFormulario() {

        String posicaoId = jTableDadosAutor.getValueAt(jTableDadosAutor.getSelectedRow(), 0).toString().toUpperCase();
        String posicaoNome = jTableDadosAutor.getValueAt(jTableDadosAutor.getSelectedRow(), 1).toString().toUpperCase();

        jTextFieldNome.setText(posicaoNome);
        autorAntiga.setId(Integer.parseInt(posicaoId));
        autorAntiga.setNomeAutor(posicaoNome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDadosAutor = new javax.swing.JTable();
        jButtonIncluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar/Pesquisar Autor do Livro");
        setMinimumSize(new java.awt.Dimension(1077, 720));
        setPreferredSize(new java.awt.Dimension(1077, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Inclui Autor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, 40));
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 480, -1));

        jTableDadosAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ));
        jTableDadosAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDadosAutorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDadosAutor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 582, 450));

        jButtonIncluir.setText("INCLUIR");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, 90, 50));

        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, 90, 50));

        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 630, 90, 50));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel17.setText("_ _ _ _ _ _ _ ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 70, 30));

        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, 90, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/imagem/magnifying-glass.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, 30));

        jLabel1.setText("Pesquisar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 30));

        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 490, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel6.setText("F A T E S G ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, 20));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel18.setText("B i b l i o ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 100, 40));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("_ _ _ _ _ _ _ _ _ ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 90, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel7.setText("P r o j e t o");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 20));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText(" t e c h");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/imagem/blur corte tela principal.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed

        try {
            

            autorAtual.setNomeAutor(jTextFieldNome.getText());

            controleAutor.incluir(autorAtual);

            imprimirDadosnaGrid(controleAutor.recuperar());

           listaAutores = controleAutor.recuperar();

            limparTela();

            JOptionPane.showMessageDialog(rootPane, "Cadastro realizado com sucesso!");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed

        try {
  
            autorAtual.setId(autorAntiga.getId());
            autorAtual.setNomeAutor(jTextFieldNome.getText());

            controleAutor.alterarAutor(autorAntiga, autorAtual);

            imprimirDadosnaGrid(controleAutor.recuperar());

            limparTela();

            JOptionPane.showMessageDialog(rootPane, "Alteração Realizada com sucesso");

            listaAutores = controleAutor.recuperar();

        } catch (Exception erro) {
            JOptionPane.showConfirmDialog(rootPane, erro);
        }

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        try {
            
            if ( jTextFieldNome.getText().equals(""))  JOptionPane.showMessageDialog(null, "Selecione um nome para excluir !", "ERRO", JOptionPane.ERROR_MESSAGE);
            else { 
            
            controleAutor.excluir(autorAntiga.getId());

            imprimirDadosnaGrid(controleAutor.recuperar());

            limparTela();
            JOptionPane.showMessageDialog(null, "Exclusão Realizada com sucesso");

            listaAutores = controleAutor.recuperar();
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableDadosAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDadosAutorMouseClicked

        try {

            preencherFormulario();

        } catch (Exception erro) {
            JOptionPane.showConfirmDialog(null, erro);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTableDadosAutorMouseClicked

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
       
            
            TelaLivroExecutada.setVisible(true);
             TelaLivroExecutada.AtualizaComboAutor();
            dispose();
        
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed

        try {

            String textoDigitado = jTextFieldPesquisar.getText().toLowerCase(); // texto digitado na jtextfield em minuscula

            ArrayList<Autor> resultadoPesquisa = new ArrayList<>(); //lista vazia com o resultado da pesquisa
            //colaboradores == lista recuperada do arquivo
            for (Autor autor : listaAutores) {

                if ((autor.getNomeAutor().toLowerCase().trim().contains(textoDigitado))
                        || (("" + autor.getId()).toLowerCase().trim().contains(textoDigitado))) {
                    resultadoPesquisa.add(autor); // INCLUI O RESULTADO ENCONTRADO NA LISTA
                }
            }
            imprimirDadosnaGrid(resultadoPesquisa);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed
    
     public void manterTelaLivroAntiga(TelaLivro telalivro){
         
        TelaLivroExecutada = telalivro;
       
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDoAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDoAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDoAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDoAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDoAutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDadosAutor;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
