/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classeDeDados.RelatorioAluno;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.OrdenadoPorCurso_Enfase_Nome;
import persistencia.OrdenadoPorCurso_Nome;
import persistencia.OrdenadoPorEnfase_Curso_Nome;
import persistencia.OrdenadoPorEnfase_Nome;
import persistencia.OrdenadoPorNome;
import persistencia.OrdenadoPorSituacao_Curso_Nome;
import persistencia.OrdenadoPorSituacao_Nome;
import persistencia.OrdenadoPorSobrenome;

/**
 *
 * @author miguelneto
 */
public class TelaRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio() {
        initComponents();
    }

     private void imprimirNaGrid(ArrayList<RelatorioAluno> dados){
        try{
            DefaultTableModel model =  (DefaultTableModel) jTableRelatorio.getModel();
            model.setNumRows(0);
            int pos = 0;
            while(pos < dados.size()){
                String[] linha = new String[4];
                RelatorioAluno rel = dados.get(pos);
                linha[0]= rel.getNome();
                linha[1]= rel.getCurso();
                linha[2]= rel.getSituacao();
                linha[3]= rel.getEnfase();
               
                model.addRow(linha);
                pos++;
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }
      private void imprimirNaGridTratandoNome(ArrayList<RelatorioAluno> dados) {
        try {
            DefaultTableModel model = (DefaultTableModel) jTableRelatorio.getModel();
            model.setNumRows(0);
            int pos = 1;
            while (pos < dados.size()) {
                String[] linha = new String[4];
                RelatorioAluno obj = dados.get(pos);

                String[] nome = obj.getNome().split(" ");
                String sobrenome = nome[nome.length - 1];

                if (sobrenome.equalsIgnoreCase("junior")
                        || sobrenome.equalsIgnoreCase("neto")
                        || sobrenome.equalsIgnoreCase("filho")) {
                    sobrenome = nome[nome.length - 2];
                }

                linha[0] = sobrenome.toUpperCase() + ", " + nome[0];
                linha[1] = obj.getCurso();
                linha[2] = obj.getSituacao();
                linha[3] = obj.getEnfase();
                model.addRow(linha);
                pos++;
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelatorio = new javax.swing.JTable();
        jButtonSituacao_Nome = new javax.swing.JButton();
        jButtonCurso_Nome = new javax.swing.JButton();
        jButtonEnfaseNome = new javax.swing.JButton();
        jButtonSobrenome = new javax.swing.JButton();
        jButtonNOME = new javax.swing.JButton();
        jButtonSituCursNome = new javax.swing.JButton();
        jButtonEnfaCurNome = new javax.swing.JButton();
        jButtonCurEnfNom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1123, 543));
        setSize(new java.awt.Dimension(1123, 543));

        jTableRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Curso", "Situação", "Ênfase"
            }
        ));
        jScrollPane1.setViewportView(jTableRelatorio);

        jButtonSituacao_Nome.setText("Situação e Nome");
        jButtonSituacao_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSituacao_NomeActionPerformed(evt);
            }
        });

        jButtonCurso_Nome.setText("Curso e Nome");
        jButtonCurso_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCurso_NomeActionPerformed(evt);
            }
        });

        jButtonEnfaseNome.setText("Ênfase e nome");
        jButtonEnfaseNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnfaseNomeActionPerformed(evt);
            }
        });

        jButtonSobrenome.setText("Sobrenome");
        jButtonSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobrenomeActionPerformed(evt);
            }
        });

        jButtonNOME.setText("Nome");
        jButtonNOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNOMEActionPerformed(evt);
            }
        });

        jButtonSituCursNome.setText("Situação, Curso e Nome ");
        jButtonSituCursNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSituCursNomeActionPerformed(evt);
            }
        });

        jButtonEnfaCurNome.setText("Ênfase, Curso e Nome");
        jButtonEnfaCurNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnfaCurNomeActionPerformed(evt);
            }
        });

        jButtonCurEnfNom.setText("Curso, Ênfase e Nome ");
        jButtonCurEnfNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCurEnfNomActionPerformed(evt);
            }
        });

        jLabel1.setText("Ordenar por:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSobrenome)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEnfaseNome)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCurso_Nome)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSituacao_Nome)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSituCursNome)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEnfaCurNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCurEnfNom))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnfaseNome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCurso_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSituacao_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSituCursNome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnfaCurNome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCurEnfNom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobrenomeActionPerformed


 try{
              
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorSobrenome objeto = new OrdenadoPorSobrenome(nome);
            imprimirNaGridTratandoNome(objeto.listagemDeRelatorio());
      
          }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
        




        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSobrenomeActionPerformed

    private void jButtonNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNOMEActionPerformed

          try{
              
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorNome objeto = new OrdenadoPorNome(nome);
            imprimirNaGrid(objeto.listagemDeRelatorio());
      
          }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNOMEActionPerformed

    private void jButtonCurso_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCurso_NomeActionPerformed

 try{
              
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorCurso_Nome objeto = new OrdenadoPorCurso_Nome(nome);
            imprimirNaGrid(objeto.listagemDeRelatorio());
      
          }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }




        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCurso_NomeActionPerformed

    private void jButtonSituacao_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSituacao_NomeActionPerformed
          try{
            
            String nome = "./src/dados/RelatorioDasEnfases.csv";
             OrdenadoPorSituacao_Nome objeto = new OrdenadoPorSituacao_Nome(nome);
            imprimirNaGrid(objeto.listagemDeRelatorio());
      
          }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSituacao_NomeActionPerformed

    private void jButtonEnfaseNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnfaseNomeActionPerformed
        try{
              
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorEnfase_Nome objeto = new  OrdenadoPorEnfase_Nome(nome);
            imprimirNaGrid(objeto.listagemDeRelatorio());
      
          }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonEnfaseNomeActionPerformed

    private void jButtonSituCursNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSituCursNomeActionPerformed
        try{
              
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorSituacao_Curso_Nome objeto = new  OrdenadoPorSituacao_Curso_Nome(nome);
            imprimirNaGrid(objeto.listagemDeRelatorio());
      
          }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonSituCursNomeActionPerformed

    private void jButtonEnfaCurNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnfaCurNomeActionPerformed
        try{
              
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorEnfase_Curso_Nome objeto = new  OrdenadoPorEnfase_Curso_Nome(nome);
            imprimirNaGrid(objeto.listagemDeRelatorio());
      
          }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonEnfaCurNomeActionPerformed

    private void jButtonCurEnfNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCurEnfNomActionPerformed
       try{
              
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorCurso_Enfase_Nome objeto = new   OrdenadoPorCurso_Enfase_Nome(nome);
            imprimirNaGrid(objeto.listagemDeRelatorio());
      
          }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonCurEnfNomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCurEnfNom;
    private javax.swing.JButton jButtonCurso_Nome;
    private javax.swing.JButton jButtonEnfaCurNome;
    private javax.swing.JButton jButtonEnfaseNome;
    private javax.swing.JButton jButtonNOME;
    private javax.swing.JButton jButtonSituCursNome;
    private javax.swing.JButton jButtonSituacao_Nome;
    private javax.swing.JButton jButtonSobrenome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRelatorio;
    // End of variables declaration//GEN-END:variables
}
